name: 'Check Language'
description: 'Runs a script to check for unacceptable language'

runs:
  using: 'composite'
  steps:
    - name: run script
      shell: bash
      run: |
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then  # if OS is linux
          git config --global --add safe.directory $PWD
        fi
        chmod -R oug+x ${GITHUB_ACTION_PATH}/check-unacceptable-language.sh
        ${GITHUB_ACTION_PATH}/check-unacceptable-language.sh

branding:
  icon: 'server'
  color: 'green'